[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ansari-backend"
version = "0.1.0"
description = "Ansari is an AI assistant to enhance understanding and practice of Islam."
authors = [
    { name = "Ansari Project", email = "feedback@ansari.chat" }
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/ansari-project/ansari-backend"
Documentation = "https://github.com/ansari-project/ansari-backend"
Source = "https://github.com/ansari-project/ansari-backend"
Tracker = "https://github.com/ansari-project/ansari-backend/issues"

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "W"]
lint.ignore = ["E501"]